### ISSUE TITLE
请问, boost::ajson 报错,说 "boost"不明确 是怎么回事?

### ISSUE THREAD

**Issue by solobear** [lordoffox/ajson#1]
请问, boost::ajson 报错,说 "boost"不明确 是怎么回事?

VS2013, 配置了boost, rapidjson也有.

错误  3   error C2440: “=”: 无法从“rapidjson::GenericMemberIterator<false,Encoding,Allocator>”转换为“rapidjson::GenericMember<Encoding,Allocator> *”    c:\users\administrator\documents\visual studio 2013\projects\outsourcing.solutions\55likemw\cxtrademw\cxtradespiimpl.cpp    16  1   CXTradeMW

5   IntelliSense:  "boost" 不明确    c:\Users\Administrator\Documents\Visual Studio 2013\Projects\Outsourcing.Solutions\55LikeMW\CXTradeMW\CXTradeSpiImpl.cpp    12  17  CXTradeMW

```
6   IntelliSense:  不存在从 "rapidjson::GenericMemberIterator<false, rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>" 到 "rapidjson::GenericMember<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>> *" 的适当转换函数    c:\Users\Administrator\Documents\Visual Studio 2013\Projects\Outsourcing.Solutions\55LikeMW\CXTradeMW\CXTradeSpiImpl.cpp    16  1   CXTradeMW
```

**Comment by lordoffox** [comment]
你的rapidjson版本比较高了，我做这个库时，rapidjson的版本较低

**Comment by lordoffox** [comment]
我上传了一个针对高版本的ajson，你可以试试看

**Comment by solobear** [comment]
谢谢！

------------------ 原始邮件 ------------------
发件人: "丁宁"notifications@github.com; 
发送时间: 2014年10月8日(星期三) 下午2:49
收件人: "lordoffox/ajson"ajson@noreply.github.com; 
抄送: "SoloBear"156709038@qq.com; 
主题: Re: [ajson] 请问, boost::ajson 报错,说 "boost"不明确 是怎么回事? (#1)

我上传了一个针对高版本的ajson，你可以试试看
