### ISSUE TITLE
utf8-bom file check fail

### ISSUE THREAD

**Issue by denghe** [lordoffox/ajson#10]
warning: result of comparison of constant 239 with expression of type 'char' is always false [-Wtautological-constant-out-of-range-compare]
      if (buffer[0] == 0xEF && buffer[1] == 0xBB && buffer[2] == 0xBF)

**Comment by lordoffox** [comment]
auto ubuffer = reinterpret_cast<unsigned char*>(buffer);
code is update earlier，plz update to new version。
