### ISSUE TITLE
判断一个类型是否具有emplace_back方法的正确姿势

### ISSUE THREAD

**Issue by lichao2014** [lordoffox/ajson#5]
`template<typename T, typename = void>
struct has_emplace_back : std::false_type {};

template<typename T>
struct has_emplace_back <T, decltype(std::declval<T>().emplace_back(), void())> : std::true_type {};`

替换你那个is_emplace_back_able数值型元函数可好？

**Comment by lordoffox** [comment]
代码貌似不全吧
